/**
 * Incidents.jsx
 *
 * Changes from base:
 *  - Fix 4: Auto geo-tag — on modal open, calls useUserLocation to get GPS coords,
 *            then reverse-geocodes via /api/geocode/reverse for a human-readable label.
 *  - Fix 5: i18n — toast messages use t() from LanguageContext.
 *  - Fix 6: Offline queuing — if navigator.onLine is false OR fetch throws a network
 *            error, the report is saved to localStorage['sih_offline_incidents'] and
 *            synced automatically when the browser goes online.
 */
import { incidents as initialMockIncidents } from '../data/mockData';
import { Badge } from '../components/common/Badge';
import { PageHeader } from '../components/common/PageHeader';
import { useNavigate } from 'react-router-dom';
import { Modal } from '../components/common/Modal';
import {
  BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer, Cell, LabelList
} from 'recharts';
import { MapContainer, TileLayer, Marker, Popup } from 'react-leaflet';
import L from 'leaflet';
import 'leaflet/dist/leaflet.css';
import toast from 'react-hot-toast';
import { useState, useMemo, useRef, useEffect, useCallback } from 'react';
import { Camera, X, MapPin, Loader, RefreshCw, Eye } from 'lucide-react';
import { useUserLocation } from '../hooks/useUserLocation';
import { reverseGeocode, incidentsAPI } from '../services/api';
import { useLang } from '../i18n/LanguageContext';
import { useSocket } from '../hooks/useSocket';

const formatLiveIncident = (item) => {
  const shortId = item._id ? `INC-${item._id.slice(-4).toUpperCase()}` : (item.id || 'INC-LIVE');
  const typeMap = {
    landslide: 'Landslide',
    rockfall: 'Landslide',
    flooding: 'Heavy Rainfall',
    heavy_rain: 'Heavy Rainfall',
    road_damage: 'Bridge / Road Damage',
    bridge_damage: 'Bridge / Road Damage',
    accident: 'Mechanical Breakdown',
    breakdown: 'Mechanical Breakdown',
    overspeeding: 'Overspeeding',
  };
  const rawType = (item.incident_type || item.type || 'landslide').toLowerCase();
  const cause = typeMap[rawType] || 'Landslide';
  const displayType = rawType === 'landslide' ? 'Landslide' :
                      rawType === 'rockfall' ? 'Rockfall' :
                      rawType === 'road_damage' ? 'Bridge Damage' :
                      rawType === 'flooding' ? 'Heavy Rainfall' :
                      rawType.charAt(0).toUpperCase() + rawType.slice(1);

  const roadName = item.road_segment_id?.road_name || item.road_name || item.locationLabel || 'NER Corridor';
  const district = (item.road_segment_id?.district || item.district) ? `, ${item.road_segment_id?.district || item.district}` : '';
  const location = `${roadName}${district}`;
  const rawSev = (item.reported_risk_level || item.severity || 'CRITICAL').toUpperCase();
  const severity = (rawSev === 'HIGH' || rawSev === 'CRITICAL') ? 'CRITICAL' : (rawSev === 'MEDIUM' || rawSev === 'WARNING') ? 'WARNING' : 'INFO';
  const time = item.created_at
    ? new Date(item.created_at).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
    : 'Just now';

  return {
    id: shortId,
    rawId: item._id || item.id,
    officerName: item.field_officer_name || item.reportedBy || 'Field Officer',
    type: displayType,
    cause: cause,
    location: location,
    severity: severity,
    time: time,
    status: 'ACTIVE',
    isLive: true,
    isNew: Boolean(item.is_new ?? item.isNew ?? true),
    roadBlock: item.road_block,
    trafficCondition: item.traffic_condition,
    description: item.description,
    slope: item.slope ?? item.slope_deg,
    rainfall: item.rainfall_mm,
    lat: item.location?.coordinates?.[1] ?? item.latitude ?? null,
    lon: item.location?.coordinates?.[0] ?? item.longitude ?? null,
  };
};

// Offline queue helpers
const QUEUE_KEY = 'sih_offline_incidents';
const getQueue  = () => { try { return JSON.parse(localStorage.getItem(QUEUE_KEY) || '[]'); } catch { return []; } };
const saveQueue = (q) => localStorage.setItem(QUEUE_KEY, JSON.stringify(q));

// Fleet-ops disclaimer
const DataSourceNote = () => (
  <div style={{
    padding: '10px 14px', marginBottom: '20px', borderRadius: '6px', fontSize: '0.8rem',
    background: 'rgba(14, 165, 233, 0.08)', border: '1px solid rgba(14, 165, 233, 0.25)',
    color: 'var(--text-secondary)', display: 'flex', alignItems: 'center', gap: '8px',
  }}>
    <span style={{ color: 'var(--info)', fontWeight: 700 }}>ℹ Fleet Ops Module</span>
    Incidents listed here are illustrative fleet-logistics scenario data,
    not real events generated by the landslide ML model. Real landslide risk alerts
    are on the Alerts page.
  </div>
);

const CAUSE_COLORS = {
  'Landslide':            '#ef4444',
  'Heavy Rainfall':       '#f97316',
  'Bridge / Road Damage': '#f59e0b',
  'Mechanical Breakdown': '#3b82f6',
  'Overspeeding':         '#6366f1',
};
const DEFAULT_COLOR = '#64748b';

// Hazard icon for incident map
const hazardIcon = L.divIcon({
  className: '',
  iconSize: [36, 36],
  iconAnchor: [18, 18],
  html: `<div style="
    width:36px;height:36px;border-radius:50%;
    background:rgba(239,68,68,0.22);
    border:2.5px solid #ef4444;
    display:flex;align-items:center;justify-content:center;
    font-size:18px;
    box-shadow:0 0 18px rgba(239,68,68,0.7);
  ">⚠️</div>`,
});

// ─── IncidentMapModal ─────────────────────────────────────────────────────────
const IncidentMapModal = ({ incident, onClose }) => {
  if (!incident) return null;
  const lat = incident.lat ?? 25.5;
  const lon = incident.lon ?? 92.5;

  return (
    <div
      style={{
        position: 'fixed', inset: 0, zIndex: 99990,
        background: 'rgba(2,6,23,0.78)', backdropFilter: 'blur(5px)',
        display: 'flex', alignItems: 'center', justifyContent: 'center', padding: 20,
      }}
      onClick={onClose}
    >
      <div
        style={{
          background: 'var(--white, #fff)', borderRadius: 16,
          width: 600, maxWidth: '95vw', maxHeight: '90vh',
          overflow: 'hidden', display: 'flex', flexDirection: 'column',
          boxShadow: '0 24px 80px rgba(0,0,0,0.5)',
        }}
        onClick={e => e.stopPropagation()}
      >
        {/* Header */}
        <div style={{
          background: 'linear-gradient(135deg,#dc2626,#b91c1c)',
          padding: '16px 20px', color: '#fff',
          display: 'flex', justifyContent: 'space-between', alignItems: 'center',
        }}>
          <div>
            <div style={{ fontWeight: 800, fontSize: '1rem', display: 'flex', alignItems: 'center', gap: 7 }}>
              <MapPin size={16} /> {incident.location || 'Incident Location'}
            </div>
            <div style={{ fontSize: '0.75rem', opacity: 0.85, marginTop: 3 }}>
              {incident.id} · {incident.type} · {incident.severity}
            </div>
          </div>
          <button onClick={onClose}
            style={{ background: 'rgba(255,255,255,0.2)', border: 'none', borderRadius: '50%', width: 30, height: 30, cursor: 'pointer', color: '#fff', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
            <X size={15} />
          </button>
        </div>

        {/* Map */}
        <div style={{ height: 320, flex: 1 }}>
          <MapContainer center={[lat, lon]} zoom={12} style={{ height: '100%', width: '100%' }} zoomControl={true}>
            <TileLayer
              url="https://tiles.stadiamaps.com/tiles/alidade_smooth/{z}/{x}/{y}{r}.png"
              attribution="&copy; OpenStreetMap contributors"
            />
            <Marker position={[lat, lon]} icon={hazardIcon}>
              <Popup>
                <div style={{ padding: '4px 6px' }}>
                  <div style={{ fontWeight: 800, color: '#dc2626', fontSize: '0.85rem' }}>⚠️ {incident.type}</div>
                  <div style={{ fontSize: '0.8rem', color: '#0f172a', fontWeight: 600, marginTop: 2 }}>{incident.location}</div>
                  {incident.roadBlock && incident.roadBlock !== 'none' && (
                    <div style={{ fontSize: '0.72rem', color: '#ef4444', fontWeight: 600, marginTop: 2 }}>Blockage: {incident.roadBlock.toUpperCase()}</div>
                  )}
                </div>
              </Popup>
            </Marker>
          </MapContainer>
        </div>

        {/* Info Footer */}
        <div style={{ padding: '12px 20px', display: 'flex', gap: 16, flexWrap: 'wrap', borderTop: '1px solid var(--line, #e2e8f0)', background: 'var(--surface, #f8fafc)' }}>
          {incident.roadBlock && incident.roadBlock !== 'none' && (
            <div style={{ fontSize: '0.8rem' }}>
              <span style={{ color: 'var(--slate)', marginRight: 4 }}>Blockage:</span>
              <span style={{ fontWeight: 700, color: '#ef4444' }}>{incident.roadBlock.toUpperCase()}</span>
            </div>
          )}
          {incident.slope != null && (
            <div style={{ fontSize: '0.8rem' }}>
              <span style={{ color: 'var(--slate)', marginRight: 4 }}>Slope:</span>
              <span style={{ fontWeight: 700 }}>{incident.slope}°</span>
            </div>
          )}
          {incident.rainfall != null && (
            <div style={{ fontSize: '0.8rem' }}>
              <span style={{ color: 'var(--slate)', marginRight: 4 }}>Rainfall:</span>
              <span style={{ fontWeight: 700 }}>{incident.rainfall} mm</span>
            </div>
          )}
          <div style={{ fontSize: '0.8rem' }}>
            <span style={{ color: 'var(--slate)', marginRight: 4 }}>Officer:</span>
            <span style={{ fontWeight: 700 }}>{incident.officerName}</span>
          </div>
          <div style={{ fontSize: '0.78rem', color: 'var(--slate)', fontFamily: 'monospace' }}>
            {lat.toFixed(5)}, {lon.toFixed(5)}
          </div>
        </div>
      </div>
    </div>
  );
};

export const Incidents = () => {
  const navigate = useNavigate();
  const { t } = useLang();
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [mapTarget, setMapTarget] = useState(null); // incident to view on map
  const [photoPreview, setPhotoPreview] = useState(null);
  const [photoBase64,  setPhotoBase64]  = useState(null);
  const [deaths,       setDeaths]       = useState('');
  const [injuries,     setInjuries]     = useState('');
  const [incidentType, setIncidentType] = useState('Landslide');
  const [description,  setDescription]  = useState('');
  const [submitting,   setSubmitting]   = useState(false);

  // Location state for geo-tagging
  const [gpsCoords,     setGpsCoords]     = useState(null);   // { lat, lon }
  const [locationLabel, setLocationLabel] = useState('');
  const [locStatus,     setLocStatus]     = useState('idle'); // idle | fetching | ready | error
  const fileRef = useRef(null);

  // Geo-location hook (already used elsewhere — no new permissions needed if granted)
  const { coords, requestLocation } = useUserLocation();

  // When modal opens, request GPS and reverse-geocode
  useEffect(() => {
    if (!isModalOpen) return;

    setLocStatus('fetching');
    requestLocation();
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [isModalOpen]);

  // When coords arrive (from hook), reverse-geocode for a human-readable label
  useEffect(() => {
    if (!isModalOpen || !coords) return;

    setGpsCoords({ lat: coords.lat, lon: coords.lon });
    setLocStatus('fetching');

    reverseGeocode(coords.lat, coords.lon)
      .then(result => {
        setLocationLabel(result.short_name || result.display_name || `${coords.lat.toFixed(5)}, ${coords.lon.toFixed(5)}`);
        setLocStatus('ready');
      })
      .catch(() => {
        setLocationLabel(`${coords.lat.toFixed(5)}, ${coords.lon.toFixed(5)}`);
        setLocStatus('ready');
      });
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [coords, isModalOpen]);

  // ── Offline sync ─────────────────────────────────────────────────────────
  const syncOfflineQueue = useCallback(async () => {
    const queue = getQueue();
    if (queue.length === 0) return;

    let synced = 0;
    const remaining = [];
    for (const item of queue) {
      try {
        await incidentsAPI.create(item);
        synced++;
      } catch {
        remaining.push(item);
      }
    }
    saveQueue(remaining);
    if (synced > 0) toast.success(`${synced} ${t('synced_queued')}`);
  }, [t]);

  useEffect(() => {
    window.addEventListener('online', syncOfflineQueue);
    return () => window.removeEventListener('online', syncOfflineQueue);
  }, [syncOfflineQueue]);

  // ── Photo handling ────────────────────────────────────────────────────────
  const handlePhoto = (e) => {
    const file = e.target.files?.[0];
    if (!file) return;
    setPhotoPreview(URL.createObjectURL(file));

    // Convert to base64 for offline storage
    const reader = new FileReader();
    reader.onload = (ev) => setPhotoBase64(ev.target.result);
    reader.readAsDataURL(file);
  };

  // ── Submit ────────────────────────────────────────────────────────────────
  const handleSubmit = async () => {
    setSubmitting(true);

    const payload = {
      type:        incidentType.toUpperCase().replace(/ /g, '_').replace('/', '_'),
      severity:    'MEDIUM',
      description: description || `${incidentType} reported via field officer app`,
      location: {
        type: 'Point',
        coordinates: gpsCoords ? [gpsCoords.lon, gpsCoords.lat] : [93.0, 25.3],
      },
      locationLabel: locationLabel || 'Unknown',
      reportedBy:    'field_officer',
      photoUrl:      photoBase64 || null,
      deaths:        parseInt(deaths)   || 0,
      injuries:      parseInt(injuries) || 0,
    };

    // Try live submit; fall back to offline queue if network is down or fails
    if (!navigator.onLine) {
      const queue = getQueue();
      saveQueue([...queue, payload]);
      toast(t('saved_offline'), { icon: '📴' });
      _resetForm();
      return;
    }

    try {
      await incidentsAPI.create(payload);
      toast.success(t('incident_reported'));
      _resetForm();
    } catch (err) {
      // Network error — queue offline
      if (err.message?.includes('Failed to fetch') || err.message?.includes('NetworkError')) {
        const queue = getQueue();
        saveQueue([...queue, payload]);
        toast(t('saved_offline'), { icon: '📴' });
        _resetForm();
      } else {
        toast.error(`Submit failed: ${err.message}`);
        setSubmitting(false);
      }
    }
  };

  const _resetForm = () => {
    setIsModalOpen(false);
    setPhotoPreview(null);
    setPhotoBase64(null);
    setDeaths('');
    setInjuries('');
    setDescription('');
    setIncidentType('Landslide');
    setGpsCoords(null);
    setLocationLabel('');
    setLocStatus('idle');
    setSubmitting(false);
  };

  // ── Live Incidents State & Socket Sync ──────────────────────────────────────
  const [incidentList, setIncidentList] = useState(initialMockIncidents);
  const [loadingLive,  setLoadingLive]  = useState(true);
  const { socket } = useSocket();

  const loadIncidents = useCallback(async () => {
    setLoadingLive(true);
    try {
      const baseUrl = import.meta.env.VITE_API_URL || '';
      const res = await fetch(`${baseUrl}/api/road-incidents`);
      const data = await res.json();
      if (data.success && Array.isArray(data.incidents) && data.incidents.length > 0) {
        const liveFormatted = data.incidents.map(item => ({
          ...formatLiveIncident(item),
          isNew: Boolean(item.is_new ?? false),
        }));
        const liveIds = new Set(liveFormatted.map(i => i.id));
        const merged = [...liveFormatted, ...initialMockIncidents.filter(i => !liveIds.has(i.id))];
        setIncidentList(merged);
      } else {
        setIncidentList(initialMockIncidents);
      }
    } catch {
      setIncidentList(initialMockIncidents);
    } finally {
      setLoadingLive(false);
    }
  }, []);

  useEffect(() => {
    loadIncidents();
  }, [loadIncidents]);

  useEffect(() => {
    const s = socket.current;
    if (!s) return;

    const handleNewIncident = (incoming) => {
      const formatted = formatLiveIncident(incoming);
      formatted.isNew = true;
      setIncidentList(prev => [formatted, ...prev.filter(x => x.id !== formatted.id)]);
      toast.success(`New incident reported: ${formatted.type} on ${formatted.location}`, { icon: '🚨' });
    };

    s.on('incident_created', handleNewIncident);
    return () => {
      s.off('incident_created', handleNewIncident);
    };
  }, [socket]);

  // ── Chart data ────────────────────────────────────────────────────────────
  const causeData = useMemo(() => {
    const counts = {};
    incidentList.forEach(inc => {
      const cause = inc.cause ?? inc.type ?? 'Other';
      counts[cause] = (counts[cause] ?? 0) + 1;
    });
    return Object.entries(counts)
      .map(([cause, count]) => ({ cause, count }))
      .sort((a, b) => b.count - a.count);
  }, [incidentList]);

  const total            = incidentList.length;
  const landslideCount   = causeData.find(d => d.cause === 'Landslide')?.count ?? 0;
  const landslidePercent = total > 0 ? Math.round((landslideCount / total) * 100) : 0;

  const severityOrder   = { CRITICAL: 0, WARNING: 1, INFO: 2 };
  const sortedIncidents = useMemo(() => {
    return [...incidentList].sort((a, b) => {
      if (a.isNew && !b.isNew) return -1;
      if (!a.isNew && b.isNew) return 1;
      return (severityOrder[a.severity] ?? 9) - (severityOrder[b.severity] ?? 9);
    });
  }, [incidentList]);

  const modalFooter = (
    <>
      <button className="btn btn-secondary" onClick={_resetForm} disabled={submitting}>Cancel</button>
      <button className="btn btn-primary" onClick={handleSubmit} disabled={submitting}>
        {submitting ? 'Submitting…' : 'Submit Report'}
      </button>
    </>
  );

  return (
    <div>
      <PageHeader
        title="Incident Management"
        description="Monitor and report GIS anomalies, roadblocks, and field incidents in real time."
        actionButton={
          <div style={{ display: 'flex', gap: 8, alignItems: 'center' }}>
            <button
              className="btn btn-secondary"
              onClick={loadIncidents}
              disabled={loadingLive}
              style={{ display: 'flex', alignItems: 'center', gap: 6, padding: '7px 12px', fontSize: '0.82rem' }}
            >
              <RefreshCw size={13} className={loadingLive ? 'spin' : ''} /> Refresh
            </button>
            <button className="btn btn-primary" onClick={() => navigate('/incident-report')}>
              + Report Incident
            </button>
          </div>
        }
      />
      <DataSourceNote />

      {/* Cause Breakdown Chart */}
      <div className="card" style={{ marginBottom: '24px' }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '4px' }}>
          <h3 style={{ fontSize: '1rem', fontWeight: 700, margin: 0 }}>Incidents by Root Cause</h3>
          <div style={{
            fontSize: '0.78rem', padding: '4px 10px', borderRadius: '10px',
            background: 'rgba(239,68,68,0.12)', color: '#ef4444',
            border: '1px solid rgba(239,68,68,0.35)', fontWeight: 600,
          }}>
            🔴 Landslides account for {landslidePercent}% of reported incidents this period
          </div>
        </div>
        <div style={{ fontSize: '0.75rem', color: 'var(--text-secondary)', marginBottom: '18px' }}>
          Horizontal bars sorted by frequency — live updates from field reports
        </div>

        <ResponsiveContainer width="100%" height={causeData.length * 44 + 20}>
          <BarChart layout="vertical" data={causeData} margin={{ top: 0, right: 60, left: 0, bottom: 0 }} barSize={20}>
            <XAxis type="number" stroke="var(--border)" tick={{ fill: 'var(--text-secondary)', fontSize: 11 }} allowDecimals={false} />
            <YAxis type="category" dataKey="cause" width={160} stroke="none" tick={{ fill: 'var(--text-primary)', fontSize: 12, fontWeight: 500 }} />
            <Tooltip
              cursor={{ fill: 'rgba(255,255,255,0.04)' }}
              contentStyle={{ backgroundColor: 'var(--surface-elevated)', border: '1px solid var(--border)', borderRadius: '6px', fontSize: '0.82rem' }}
              formatter={(value) => [`${value} incident${value !== 1 ? 's' : ''}`, 'Count']}
            />
            <Bar dataKey="count" radius={[0, 4, 4, 0]}>
              {causeData.map(entry => <Cell key={entry.cause} fill={CAUSE_COLORS[entry.cause] ?? DEFAULT_COLOR} />)}
              <LabelList dataKey="count" position="right" style={{ fill: 'var(--text-secondary)', fontSize: 12, fontWeight: 600 }} />
            </Bar>
          </BarChart>
        </ResponsiveContainer>

        <div style={{ display: 'flex', gap: '16px', flexWrap: 'wrap', marginTop: '16px', paddingTop: '12px', borderTop: '1px solid var(--border)' }}>
          {causeData.map(({ cause }) => (
            <div key={cause} style={{ display: 'flex', alignItems: 'center', gap: '6px', fontSize: '0.74rem', color: 'var(--text-secondary)' }}>
              <span style={{ width: 10, height: 10, borderRadius: 2, background: CAUSE_COLORS[cause] ?? DEFAULT_COLOR, flexShrink: 0 }} />
              {cause}
            </div>
          ))}
        </div>
      </div>

      {/* Incidents Table */}
      <div className="card">
        <div className="table-container">
          <table>
            <thead>
              <tr>
                <th>Field Officer</th>
                <th>Type</th>
                <th>Root Cause</th>
                <th>Location</th>
                <th>Severity</th>
                <th>Time Reported</th>
                <th>Status</th>
                <th>Map</th>
              </tr>
            </thead>
            <tbody>
              {sortedIncidents.map(inc => (
                <tr key={inc.rawId || inc.id} style={inc.isNew ? { background: 'rgba(239, 68, 68, 0.05)' } : undefined}>
                  <td style={{ padding: '10px 16px', fontSize: '0.82rem' }}>
                    <div style={{ fontWeight: 600, color: 'var(--ink)' }}>{inc.officerName}</div>
                    <div style={{ fontSize: '0.72rem', color: 'var(--slate)', marginTop: 2 }}>{inc.id}</div>
                    {inc.isNew && (
                      <span style={{
                        display: 'inline-block', marginTop: 4,
                        fontSize: '0.62rem',
                        fontWeight: 800,
                        color: '#ef4444',
                        background: 'rgba(239,68,68,0.14)',
                        padding: '1px 5px',
                        borderRadius: 4,
                        border: '1px solid rgba(239,68,68,0.35)',
                        letterSpacing: '0.04em',
                      }}>
                        NEW
                      </span>
                    )}
                  </td>
                  <td>
                    <div style={{ fontWeight: 500 }}>{inc.type}</div>
                    {inc.trafficCondition && (
                      <div style={{ fontSize: '0.7rem', color: 'var(--text-secondary)' }}>
                        Traffic: {inc.trafficCondition}
                      </div>
                    )}
                  </td>
                  <td>
                    <span style={{
                      fontSize: '0.75rem', padding: '2px 8px', borderRadius: 8,
                      background: `${CAUSE_COLORS[inc.cause] ?? DEFAULT_COLOR}20`,
                      color: CAUSE_COLORS[inc.cause] ?? DEFAULT_COLOR,
                      border: `1px solid ${CAUSE_COLORS[inc.cause] ?? DEFAULT_COLOR}50`,
                      fontWeight: 600,
                    }}>
                      {inc.cause ?? inc.type}
                    </span>
                  </td>
                  <td>
                    <div>{inc.location}</div>
                    {inc.roadBlock && inc.roadBlock !== 'none' && (
                      <div style={{ fontSize: '0.7rem', color: '#ef4444', fontWeight: 600 }}>
                        Blockage: {inc.roadBlock.toUpperCase()}
                      </div>
                    )}
                    {(inc.slope != null || inc.rainfall != null) && (
                      <div style={{ fontSize: '0.7rem', color: 'var(--slate)', marginTop: 2 }}>
                        {inc.slope != null ? `Slope: ${inc.slope}°` : ''}
                        {inc.slope != null && inc.rainfall != null ? ' · ' : ''}
                        {inc.rainfall != null ? `Rain: ${inc.rainfall}mm` : ''}
                      </div>
                    )}
                  </td>
                  <td><Badge type={inc.severity === 'CRITICAL' ? 'danger' : inc.severity === 'WARNING' ? 'warning' : 'default'}>{inc.severity}</Badge></td>
                  <td>{inc.time}</td>
                  <td><Badge type={inc.status === 'ACTIVE' ? 'danger' : 'default'}>{t(inc.status) || inc.status}</Badge></td>
                  <td style={{ padding: '8px 12px', whiteSpace: 'nowrap' }}>
                    {(inc.lat != null || inc.isLive) && (
                      <button
                        onClick={() => setMapTarget(inc)}
                        style={{
                          padding: '4px 10px', borderRadius: 6,
                          background: 'linear-gradient(135deg,#0284c7,#0ea5e9)',
                          color: '#fff', border: 'none',
                          fontSize: '0.72rem', fontWeight: 700,
                          cursor: 'pointer', display: 'flex', alignItems: 'center', gap: 4,
                          boxShadow: '0 1px 6px rgba(14,165,233,0.3)',
                        }}
                      >
                        <Eye size={11} /> View
                      </button>
                    )}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      {/* Incident Map Modal */}
      {mapTarget && <IncidentMapModal incident={mapTarget} onClose={() => setMapTarget(null)} />}

      {/* Report Modal */}
      <Modal isOpen={isModalOpen} onClose={_resetForm} title="Report New Incident" footer={modalFooter}>

        {/* Incident Type */}
        <div className="form-group">
          <label className="form-label">Incident Type</label>
          <select className="form-control" value={incidentType} onChange={e => setIncidentType(e.target.value)}>
            <option>Landslide</option>
            <option>Heavy Rainfall</option>
            <option>Bridge / Road Damage</option>
            <option>Mechanical Breakdown</option>
            <option>Overspeeding</option>
            <option>Other</option>
          </select>
        </div>

        {/* Auto geo-tagged location */}
        <div className="form-group">
          <label className="form-label" style={{ display: 'flex', alignItems: 'center', gap: 5 }}>
            <MapPin size={13} />
            Location (auto geo-tagged)
          </label>

          {locStatus === 'fetching' && (
            <div style={{ display: 'flex', alignItems: 'center', gap: 7, color: 'var(--text-secondary)', fontSize: '0.82rem', padding: '8px 0' }}>
              <Loader size={13} style={{ animation: 'spin 1s linear infinite' }} />
              {t('location_fetching')}
            </div>
          )}

          {locStatus === 'ready' && gpsCoords && (
            <div style={{ background: 'var(--sky-tint)', border: '1px solid var(--sky-tint-2)', borderRadius: 8, padding: '8px 12px' }}>
              <div style={{ fontSize: '0.82rem', fontWeight: 600, color: 'var(--ink)', marginBottom: 2 }}>
                📍 {locationLabel}
              </div>
              <div style={{ fontSize: '0.72rem', color: 'var(--slate)', fontFamily: 'monospace' }}>
                {gpsCoords.lat.toFixed(6)}, {gpsCoords.lon.toFixed(6)}
              </div>
              <div style={{ fontSize: '0.68rem', color: 'var(--slate-soft)', marginTop: 3, fontStyle: 'italic' }}>
                GPS coordinates will be saved with this report
              </div>
            </div>
          )}

          {locStatus === 'idle' && (
            <div style={{ fontSize: '0.8rem', color: 'var(--text-secondary)', padding: '6px 0' }}>
              Waiting for GPS…
            </div>
          )}

          {locStatus === 'error' && (
            <div style={{ fontSize: '0.8rem', color: 'var(--danger)', padding: '6px 0' }}>
              {t('location_denied')} Coordinates will default to region centre.
            </div>
          )}
        </div>

        {/* Description */}
        <div className="form-group">
          <label className="form-label">Description</label>
          <textarea
            className="form-control"
            rows={2}
            placeholder="Brief description of the incident…"
            value={description}
            onChange={e => setDescription(e.target.value)}
            style={{ resize: 'vertical' }}
          />
        </div>

        {/* Casualties */}
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12 }}>
          <div className="form-group">
            <label className="form-label">Deaths (if any)</label>
            <input type="number" min="0" className="form-control" value={deaths}
              onChange={e => setDeaths(e.target.value)} placeholder="0" />
          </div>
          <div className="form-group">
            <label className="form-label">Injuries (if any)</label>
            <input type="number" min="0" className="form-control" value={injuries}
              onChange={e => setInjuries(e.target.value)} placeholder="0" />
          </div>
        </div>

        {/* Photo upload */}
        <div className="form-group">
          <label className="form-label" style={{ display: 'flex', alignItems: 'center', gap: 5 }}>
            <Camera size={14} /> Incident Photo (optional)
          </label>
          {photoPreview ? (
            <div style={{ position: 'relative', display: 'inline-block', marginBottom: 6 }}>
              <img src={photoPreview} alt="Preview"
                style={{ width: 160, height: 110, objectFit: 'cover', borderRadius: 8, border: '1px solid var(--line)' }} />
              <button onClick={() => { setPhotoPreview(null); setPhotoBase64(null); }}
                style={{ position: 'absolute', top: -6, right: -6, background: 'var(--danger)', color: '#fff',
                  border: 'none', borderRadius: '50%', width: 20, height: 20, cursor: 'pointer',
                  display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                <X size={11} />
              </button>
            </div>
          ) : (
            <button type="button" onClick={() => fileRef.current?.click()}
              style={{ display: 'flex', alignItems: 'center', gap: 7, padding: '8px 14px',
                background: 'var(--sky-tint)', border: '1.5px dashed var(--sky-tint-2)',
                borderRadius: 8, cursor: 'pointer', color: 'var(--slate)', fontSize: '0.82rem', fontWeight: 500 }}>
              <Camera size={14} /> Click to upload a photo
            </button>
          )}
          <input ref={fileRef} type="file" accept="image/*" style={{ display: 'none' }} onChange={handlePhoto} />
        </div>

        {/* Offline indicator */}
        {!navigator.onLine && (
          <div style={{
            padding: '8px 12px', borderRadius: 8, fontSize: '0.78rem', fontWeight: 600,
            background: 'rgba(245,158,11,0.12)', border: '1px solid rgba(245,158,11,0.35)',
            color: '#b45309', display: 'flex', alignItems: 'center', gap: 7,
          }}>
            📴 You are offline — this report will be saved locally and synced when you reconnect.
          </div>
        )}
      </Modal>
    </div>
  );
};