import { incidents } from '../data/mockData';
import { Badge } from '../components/common/Badge';
import { PageHeader } from '../components/common/PageHeader';
import { Modal } from '../components/common/Modal';
import {
  BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer, Cell, LabelList
} from 'recharts';
import toast from 'react-hot-toast';
import { useState, useMemo, useRef } from 'react';
import { Camera, X } from 'lucide-react';

// Fleet-ops disclaimer
const DataSourceNote = () => (
  <div style={{
    padding: '10px 14px', marginBottom: '20px', borderRadius: '6px', fontSize: '0.8rem',
    background: 'rgba(14, 165, 233, 0.08)', border: '1px solid rgba(14, 165, 233, 0.25)',
    color: 'var(--text-secondary)', display: 'flex', alignItems: 'center', gap: '8px',
  }}>
    <span style={{ color: 'var(--info)', fontWeight: 700 }}>ℹ Fleet Ops Module</span>
    Incidents listed here are illustrative fleet-logistics scenario data,
    not real events generated by the landslide ML model. Real landslide risk alerts
    are on the Alerts page.
  </div>
);

// Colour per root-cause bucket
const CAUSE_COLORS = {
  'Landslide':            '#ef4444',   // risk-red — landslide-related
  'Heavy Rainfall':       '#f97316',   // orange — weather
  'Bridge / Road Damage': '#f59e0b',   // amber — infrastructure
  'Mechanical Breakdown': '#3b82f6',   // blue — vehicle
  'Overspeeding':         '#6366f1',   // indigo — human
};

const DEFAULT_COLOR = '#64748b';

export const Incidents = () => {
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [photoPreview, setPhotoPreview] = useState(null);
  const [deaths,   setDeaths]   = useState('');
  const [injuries, setInjuries] = useState('');
  const fileRef = useRef(null);

  const handlePhoto = (e) => {
    const file = e.target.files?.[0];
    if (file) setPhotoPreview(URL.createObjectURL(file));
  };

  // ── Cause breakdown chart data ──────────────────────────────────────────
  const causeData = useMemo(() => {
    const counts = {};
    incidents.forEach(inc => {
      const cause = inc.cause ?? inc.type ?? 'Other';
      counts[cause] = (counts[cause] ?? 0) + 1;
    });
    return Object.entries(counts)
      .map(([cause, count]) => ({ cause, count }))
      .sort((a, b) => b.count - a.count);   // descending
  }, []);

  const total = incidents.length;
  const landslideCount = causeData.find(d => d.cause === 'Landslide')?.count ?? 0;
  const landslidePercent = total > 0 ? Math.round((landslideCount / total) * 100) : 0;

  // ── Sort incidents by severity for the table (CRITICAL first) ──────────
  const severityOrder = { CRITICAL: 0, WARNING: 1, INFO: 2 };
  const sortedIncidents = [...incidents].sort(
    (a, b) => (severityOrder[a.severity] ?? 9) - (severityOrder[b.severity] ?? 9)
  );

  const handleSubmit = () => {
    setIsModalOpen(false);
    setPhotoPreview(null); setDeaths(''); setInjuries('');
    toast.success('Incident reported successfully. Awaiting verification.');
  };

  const modalFooter = (
    <>
      <button className="btn btn-secondary" onClick={() => setIsModalOpen(false)}>Cancel</button>
      <button className="btn btn-primary" onClick={handleSubmit}>Submit Report</button>
    </>
  );

  return (
    <div>
      <PageHeader
        title="Incident Management"
        description="Monitor and report GIS anomalies and road blockages. Fleet Ops module — illustrative scenario data."
        actionButton={<button className="btn btn-primary" onClick={() => setIsModalOpen(true)}>+ Report Incident</button>}
      />
      <DataSourceNote />

      {/* ── Cause Breakdown Chart ── */}
      <div className="card" style={{ marginBottom: '24px' }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '4px' }}>
          <h3 style={{ fontSize: '1rem', fontWeight: 700, margin: 0 }}>Incidents by Root Cause</h3>
          <div style={{
            fontSize: '0.78rem', padding: '4px 10px', borderRadius: '10px',
            background: 'rgba(239,68,68,0.12)', color: '#ef4444',
            border: '1px solid rgba(239,68,68,0.35)', fontWeight: 600,
          }}>
            🔴 Landslides account for {landslidePercent}% of reported incidents this period
          </div>
        </div>
        <div style={{ fontSize: '0.75rem', color: 'var(--text-secondary)', marginBottom: '18px' }}>
          Horizontal bars sorted by frequency — highest cause at top
        </div>

        <ResponsiveContainer width="100%" height={causeData.length * 44 + 20}>
          <BarChart
            layout="vertical"
            data={causeData}
            margin={{ top: 0, right: 60, left: 0, bottom: 0 }}
            barSize={20}
          >
            <XAxis
              type="number"
              stroke="var(--border)"
              tick={{ fill: 'var(--text-secondary)', fontSize: 11 }}
              allowDecimals={false}
            />
            <YAxis
              type="category"
              dataKey="cause"
              width={160}
              stroke="none"
              tick={{ fill: 'var(--text-primary)', fontSize: 12, fontWeight: 500 }}
            />
            <Tooltip
              cursor={{ fill: 'rgba(255,255,255,0.04)' }}
              contentStyle={{
                backgroundColor: 'var(--surface-elevated)',
                border: '1px solid var(--border)',
                borderRadius: '6px',
                fontSize: '0.82rem',
              }}
              formatter={(value, name) => [`${value} incident${value !== 1 ? 's' : ''}`, 'Count']}
            />
            <Bar dataKey="count" radius={[0, 4, 4, 0]}>
              {causeData.map(entry => (
                <Cell key={entry.cause} fill={CAUSE_COLORS[entry.cause] ?? DEFAULT_COLOR} />
              ))}
              <LabelList
                dataKey="count"
                position="right"
                style={{ fill: 'var(--text-secondary)', fontSize: 12, fontWeight: 600 }}
              />
            </Bar>
          </BarChart>
        </ResponsiveContainer>

        {/* Legend */}
        <div style={{ display: 'flex', gap: '16px', flexWrap: 'wrap', marginTop: '16px', paddingTop: '12px', borderTop: '1px solid var(--border)' }}>
          {causeData.map(({ cause }) => (
            <div key={cause} style={{ display: 'flex', alignItems: 'center', gap: '6px', fontSize: '0.74rem', color: 'var(--text-secondary)' }}>
              <span style={{ width: 10, height: 10, borderRadius: 2, background: CAUSE_COLORS[cause] ?? DEFAULT_COLOR, flexShrink: 0 }} />
              {cause}
            </div>
          ))}
        </div>
      </div>

      {/* ── Incidents Table ── */}
      <div className="card">
        <div className="table-container">
          <table>
            <thead>
              <tr>
                <th>ID</th>
                <th>Type</th>
                <th>Root Cause</th>
                <th>Location</th>
                <th>Severity</th>
                <th>Time Reported</th>
                <th>Status</th>
              </tr>
            </thead>
            <tbody>
              {sortedIncidents.map(inc => (
                <tr key={inc.id}>
                  <td style={{ fontWeight: 600 }}>{inc.id}</td>
                  <td>{inc.type}</td>
                  <td>
                    <span style={{
                      fontSize: '0.75rem', padding: '2px 8px', borderRadius: 8,
                      background: `${CAUSE_COLORS[inc.cause] ?? DEFAULT_COLOR}20`,
                      color: CAUSE_COLORS[inc.cause] ?? DEFAULT_COLOR,
                      border: `1px solid ${CAUSE_COLORS[inc.cause] ?? DEFAULT_COLOR}50`,
                      fontWeight: 600,
                    }}>
                      {inc.cause ?? inc.type}
                    </span>
                  </td>
                  <td>{inc.location}</td>
                  <td><Badge>{inc.severity}</Badge></td>
                  <td>{inc.time}</td>
                  <td><Badge>{inc.status}</Badge></td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      {/* Report Modal */}
      <Modal isOpen={isModalOpen} onClose={() => setIsModalOpen(false)} title="Report New Incident" footer={modalFooter}>
        <div className="form-group">
          <label className="form-label">Incident Type</label>
          <select className="form-control">
            <option>Landslide</option>
            <option>Heavy Rainfall</option>
            <option>Bridge / Road Damage</option>
            <option>Mechanical Breakdown</option>
            <option>Overspeeding</option>
            <option>Other</option>
          </select>
        </div>
        <div className="form-group">
          <label className="form-label">Location</label>
          <input type="text" className="form-control" placeholder="e.g., NH-10 Sector B" />
        </div>

        {/* Casualties */}
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12 }}>
          <div className="form-group">
            <label className="form-label">Deaths (if any)</label>
            <input type="number" min="0" className="form-control" value={deaths}
              onChange={e => setDeaths(e.target.value)} placeholder="0" />
          </div>
          <div className="form-group">
            <label className="form-label">Injuries (if any)</label>
            <input type="number" min="0" className="form-control" value={injuries}
              onChange={e => setInjuries(e.target.value)} placeholder="0" />
          </div>
        </div>

        {/* Photo upload */}
        <div className="form-group">
          <label className="form-label" style={{ display: 'flex', alignItems: 'center', gap: 5 }}>
            <Camera size={14} /> Incident Photo (optional)
          </label>
          {photoPreview ? (
            <div style={{ position: 'relative', display: 'inline-block', marginBottom: 6 }}>
              <img src={photoPreview} alt="Preview"
                style={{ width: 160, height: 110, objectFit: 'cover', borderRadius: 8, border: '1px solid var(--line)' }} />
              <button onClick={() => setPhotoPreview(null)}
                style={{ position: 'absolute', top: -6, right: -6, background: 'var(--danger)', color: '#fff',
                  border: 'none', borderRadius: '50%', width: 20, height: 20, cursor: 'pointer',
                  display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                <X size={11} />
              </button>
            </div>
          ) : (
            <button type="button" onClick={() => fileRef.current?.click()}
              style={{ display: 'flex', alignItems: 'center', gap: 7, padding: '8px 14px',
                background: 'var(--sky-tint)', border: '1.5px dashed var(--sky-tint-2)',
                borderRadius: 8, cursor: 'pointer', color: 'var(--slate)', fontSize: '0.82rem', fontWeight: 500 }}>
              <Camera size={14} /> Click to upload a photo
            </button>
          )}
          <input ref={fileRef} type="file" accept="image/*" style={{ display: 'none' }} onChange={handlePhoto} />
        </div>
      </Modal>
    </div>
  );
};